// src/scripts/seedDatabase.ts

import admin from 'firebase-admin';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const serviceAccountPath = resolve(process.cwd(), 'serviceAccountKey.json');
const serviceAccount = JSON.parse(readFileSync(serviceAccountPath, 'utf8'));

const CLIENT_ID = 'TNwHy3I7FYSo6lWRB9zziwoAUHD3';

const siteData = {
    hero: {
        title: "Cleriston Ribeiro",
        backgroundImage: "/assets/img/hero-bg.jpg",
        typedItems: {
            ptBR: ["Ilustrador", "Caricaturista", "Concept Artist 2D"],
            en: ["Illustrator", "Caricaturist", "2D Concept Artist"],
            es: ["Ilustrador", "Caricaturista", "Artista Conceptual 2D"]
        }
    },
    social: {
        instagram: "https://www.instagram.com/cleriston_rib/",
        whatsapp: "https://wa.me/5511993533001",
        behance: "https://www.behance.net/cleristonribeiro",
        linkedin: "https://www.linkedin.com/in/cleristonrib/"
    },
    sobre: {
        titulo: { ptBR: "Sobre", en: "About", es: "Sobre mí" },
        subtitulo: { ptBR: "Um pouquinho da minha História", en: "A little bit of my story", es: "Un poquito de mi historia" },
        texto: {
            ptBR: `Sou um ilustrador brasileiro de 38 anos, casado e pai de uma linda menina de 10 anos. Atuo com ilustração desde 2008, iniciei miha carreira no estúdio Ilustra Cartoon, onde tive contato pela primeira vez com uma de minha paixões que o cartoon e a criação de ilustrações infanto-juvenis, para livros didáticos, literaturas e editoriais em geral. Em 2011, início uma nova jornada na agência de treinamentos corporativos Ideale Treinamentos, onde atuei como Ilustrador, além de desenvolver alguns trabalhos como Designer Gráfico, local onde tem grande influencia em meu estilo de ilustração até o ano de 2015.\n\nNo ano de 2015, ingressei no núcleo de Ensino Online no Senai-SP, onde desenvolvo ilustrações e animações para os cursos em diversos estilos.\n\nEm paralelo, no ano de 2018, retorno a criação de livros didáticos com algumas das maiores editoras do país, além de alguns trabalhos editoriais e publicitários.\n\nEm 2022 entrou para o time da Lemonade Illustration Agency.`,
            en: `I am a 38-year-old Brazilian illustrator, married and father of a beautiful 10-year-old girl. I have been working with illustration since 2008. I started my career at the Ilustra Cartoon studio, where I first came into contact with one of my passions, which is cartooning and creating illustrations for children and young adults, for textbooks, literature, and editorials in general. In 2011, I began a new journey at the corporate training agency Ideale Treinamentos, where I worked as an Illustrator, in addition to developing some work as a Graphic Designer, a place that greatly influenced my illustration style until 2015.\n\nIn 2015, I joined the Online Education unit at Senai-SP, where I develop illustrations and animations for courses in various styles.\n\nIn parallel, in 2018, I returned to creating textbooks with some of the largest publishers in the country, as well as some editorial and advertising work.\n\nIn 2022, I joined the Lemonade Illustration Agency team.`,
            es: `Soy un ilustrador brasileño de 38 años, casado y padre de una hermosa niña de 10 años. Trabajo con ilustración desde 2008. Comencé mi carrera en el estudio Ilustra Cartoon, donde tuve mi primer contacto con una de mis pasiones, que es el cartoon y la creación de ilustraciones para niños y jóvenes, para libros de texto, literatura y editoriales en general. En 2011, comencé una nueva etapa en la agencia de formación corporativa Ideale Treinamentos, donde trabajé como ilustrador, además de realizar algunos trabajos como diseñador gráfico, lugar que influyó mucho en mi estilo de ilustración hasta el año 2015.\n\nEn 2015, me incorporé al núcleo de Educación Online en Senai-SP, donde desarrollo ilustraciones y animaciones para los cursos en diversos estilos.\n\nParalelamente, en 2018, volví a la creación de libros de texto con algunas de las editoriales más grandes del país, además de algunos trabajos editoriales y publicitarios.\n\nEn 2022 me uní al equipo de Lemonade Illustration Agency.`
        },
        imagemPerfilUrl: "/assets/img/perfil.jpg"
    },
    portfolio: {
        titulo: { ptBR: "Portfólio", en: "Portfolio", es: "Portafolio" },
        subtitulo: { ptBR: "Desenhos digitais disponibilizadas em formato vetorial.", en: "Digital drawings available in vector format.", es: "Dibujos digitales disponibles en formato vectorial." },
        items: [
            { id: '1', titulo: { ptBR: 'Mascote Canino', en: 'Dog Mascot', es: 'Mascota Canina' }, descricao: { ptBR: 'Criado para material publicitário, como mascote de uma Petshop.', en: 'Created for advertising material, as a mascot for a Petshop.', es: 'Creado para material publicitario, como mascota de una Petshop.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_characterdesign-dog.jpg' },
            { id: '2', titulo: { ptBR: 'Caricatura Rafinha Bastos', en: 'Rafinha Bastos Caricature', es: 'Caricatura de Rafinha Bastos' }, descricao: { ptBR: 'Caricatura desenvolvida para projeto de card game dos comediantes brasileiros.', en: 'Caricature developed for a card game project of Brazilian comedians.', es: 'Caricatura desarrollada para un proyecto de juego de cartas de comediantes brasileños.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_rafinha.jpg' },
            { id: '3', titulo: { ptBR: 'O menino e a coleção', en: 'The Boy and the Collection', es: 'El Niño y la Colección' }, descricao: { ptBR: 'Desenvolvido para um app de conteúdo didático, a ilustração contém um menino e sua coleção de carrinhos de brinquedo.', en: 'Developed for an educational content app, the illustration features a boy and his toy car collection.', es: 'Desarrollado para una aplicación de contenido educativo, la ilustración muestra a un niño y su colección de coches de juguete.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_childrensapp.jpg' },
            { id: '4', titulo: { ptBR: 'O abraço', en: 'The Hug', es: 'El Abrazo' }, descricao: { ptBR: 'Desenvolvida para livro infantil, Ilustração de um avô e sua neta abraçados.', en: 'Developed for a children\'s book, an illustration of a grandfather and his granddaughter hugging.', es: 'Desarrollada para un libro infantil, una ilustración de un abuelo y su nieta abrazados.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_childrensbook.jpg' },
            { id: '5', titulo: { ptBR: 'Dançando com o vovô', en: 'Dancing with Grandpa', es: 'Bailando con el Abuelo' }, descricao: { ptBR: 'Ilustração de um avô e sua neta dançando, desenvolvida para livro infantil.', en: 'Illustration of a grandfather and his granddaughter dancing, developed for a children\'s book.', es: 'Ilustración de un abuelo y su nieta bailando, desarrollada para un libro infantil.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_childrensbook2.jpg' },
            { id: '6', titulo: { ptBR: 'Tartaruga e o futebol', en: 'Turtle and Soccer', es: 'La Tortuga y el Fútbol' }, descricao: { ptBR: 'Criada para livro infantil, uma tartaruga correndo ao encontro de uma bola de futebol.', en: 'Created for a children\'s book, a turtle running towards a soccer ball.', es: 'Creada para un libro infantil, una tortuga corriendo hacia un balón de fútbol.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_childrensbook3.jpg' },
            { id: '7', titulo: { ptBR: 'A Praça', en: 'The Square', es: 'La Plaza' }, descricao: { ptBR: 'Cenário de praça, com um pássaro em um galho de árvore, para livro didático.', en: 'A square scene, with a bird on a tree branch, for a textbook.', es: 'Escena de una plaza, con un pájaro en la rama de un árbol, para un libro de texto.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_childrensbook4.jpg' },
            { id: '8', titulo: { ptBR: 'Alô Vovô!', en: 'Hello Grandpa!', es: '¡Hola Abuelo!' }, descricao: { ptBR: 'Avô conversando com seu neto através de um tablet, para campanha publicitária.', en: 'Grandfather talking to his grandson via a tablet, for an advertising campaign.', es: 'Abuelo hablando con su nieto a través de una tableta, para una campaña publicitaria.' }, categoria: 'publi', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration.jpg' },
            { id: '9', titulo: { ptBR: 'Voltando das compras', en: 'Back from Shopping', es: 'Volviendo de las Compras' }, descricao: { ptBR: 'Homem saindo de uma padaria em direção ao seu carro, para app de material didático.', en: 'Man leaving a bakery towards his car, for an educational material app.', es: 'Hombre saliendo de una panadería hacia su coche, para una aplicación de material educativo.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_childrensbook5.jpg' },
            { id: '10', titulo: { ptBR: 'Festa no Céu', en: 'Party in the Sky', es: 'Fiesta en el Cielo' }, descricao: { ptBR: 'História em quadrinhos para livro didático representando o clássico “Uma festa no céu”.', en: 'Comic strip for a textbook representing the classic "Party in the Sky".', es: 'Historieta para un libro de texto que representa el clásico "Fiesta en el Cielo".' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_comicsart-characterdesign.jpg' },
            { id: '11', titulo: { ptBR: 'Frank', en: 'Frank', es: 'Frank' }, descricao: { ptBR: 'Estudo de personagem para material publicitário com tema de Hallowen.', en: 'Character study for advertising material with a Halloween theme.', es: 'Estudio de personaje para material publicitario con temática de Halloween.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_characterdesign.jpg' },
            { id: '12', titulo: { ptBR: 'Turma no parque', en: 'Group in the Park', es: 'Grupo en el Parque' }, descricao: { ptBR: 'HQ para material didático mostrando sentimentos de crianças na natureza.', en: 'Comic for educational material showing children\'s feelings in nature.', es: 'Historieta para material didáctico que muestra los sentimientos de los niños en la naturaleza.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_comicsart-characterdesign2.jpg' },
            { id: '13', titulo: { ptBR: 'Festa no céu detalhado', en: 'Party in the Sky (Detail)', es: 'Fiesta en el Cielo (Detalle)' }, descricao: { ptBR: 'Cena em detalhe do clássico “Festa no céu” em quadrinhos.', en: 'Detailed scene from the classic "Party in the Sky" in comics.', es: 'Escena detallada del clásico "Fiesta en el Cielo" en historietas.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_comicsart.jpg' },
            { id: '14', titulo: { ptBR: 'O Cangaceiro', en: 'The Cangaceiro', es: 'El Cangaceiro' }, descricao: { ptBR: 'Ilustração representando um cangaceiro para material didático.', en: 'Illustration representing a cangaceiro for educational material.', es: 'Ilustración que representa a un cangaceiro para material didáctico.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-cangaceiro.jpg' },
            { id: '15', titulo: { ptBR: 'A cidade', en: 'The City', es: 'La Ciudad' }, descricao: { ptBR: 'Representação de cidade fictícia para abertura de capítulo de livro.', en: 'Representation of a fictional city for a book chapter opening.', es: 'Representación de una ciudad ficticia para la apertura de un capítulo de un libro.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-city.jpg' },
            { id: '16', titulo: { ptBR: 'A família', en: 'The Family', es: 'La Familia' }, descricao: { ptBR: 'Ilustração de uma família assistindo televisão, para livro didático.', en: 'Illustration of a family watching television, for a textbook.', es: 'Ilustración de una familia viendo la televisión, para un libro de texto.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-family.jpg' },
            { id: '17', titulo: { ptBR: 'Super herói', en: 'Superhero', es: 'Superhéroe' }, descricao: { ptBR: 'Personagem criado para ilustrar página de livro didático.', en: 'Character created to illustrate a textbook page.', es: 'Personaje creado para ilustrar la página de un libro de texto.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-hero.jpg' },
            { id: '18', titulo: { ptBR: 'Caricatura Fábio Porchat', en: 'Fábio Porchat Caricature', es: 'Caricatura de Fábio Porchat' }, descricao: { ptBR: 'Caricatura para projeto de card game de comediantes.', en: 'Caricature for a comedians card game project.', es: 'Caricatura para un proyecto de juego de cartas de comediantes.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_Porchat.jpg' },
            { id: '19', titulo: { ptBR: 'O Camaleão', en: 'The Chameleon', es: 'El Camaleón' }, descricao: { ptBR: 'Ilustração de um camaleão para material didático.', en: 'Illustration of a chameleon for educational material.', es: 'Ilustración de un camaleón para material educativo.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-lizard.jpg' },
            { id: '20', titulo: { ptBR: 'O Marciano', en: 'The Martian', es: 'El Marciano' }, descricao: { ptBR: 'Representação lúdica de uma fazenda em Marte.', en: 'Playful representation of a farm on Mars.', es: 'Representación lúdica de una granja en Marte.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-martian_farm.jpg' },
            { id: '21', titulo: { ptBR: 'A artista', en: 'The Artist (Female)', es: 'La Artista' }, descricao: { ptBR: 'Menina pintando uma tela em sala de aula.', en: 'Girl painting a canvas in a classroom.', es: 'Niña pintando un lienzo en un aula.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-painter.jpg' },
            { id: '22', titulo: { ptBR: 'Caricatura Diogo Portugal', en: 'Diogo Portugal Caricature', es: 'Caricatura de Diogo Portugal' }, descricao: { ptBR: 'Caricatura para projeto de card game de comediantes.', en: 'Caricature for a comedians card game project.', es: 'Caricatura para un proyecto de juego de cartas de comediantes.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_Diogo Portugal.jpg' },
            { id: '23', titulo: { ptBR: 'Grupo de pessoas', en: 'Group of People', es: 'Grupo de Personas' }, descricao: { ptBR: 'Grupo diverso de pessoas em cidade do nordeste brasileiro.', en: 'Diverse group of people in a city in northeastern Brazil.', es: 'Grupo diverso de personas en una ciudad del noreste de Brasil.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-peoples.jpg' },
            { id: '24', titulo: { ptBR: 'Alfaiate', en: 'Tailor', es: 'Sastre' }, descricao: { ptBR: 'Um velho alfaiate trabalhando em seu ateliê.', en: 'An old tailor working in his workshop.', es: 'Un sastre anciano trabajando en su taller.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-tailor.jpg' },
            { id: '25', titulo: { ptBR: 'A Goleira', en: 'The Goalkeeper (Female)', es: 'La Portera' }, descricao: { ptBR: 'Ilustração para incentivo do futebol feminino.', en: 'Illustration to encourage women\'s soccer.', es: 'Ilustración para fomentar el fútbol femenino.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook-thegoalkeeper.jpg' },
            { id: '26', titulo: { ptBR: 'Dom Pedro II', en: 'Dom Pedro II', es: 'Dom Pedro II' }, descricao: { ptBR: 'Caricatura do imperador brasileiro Dom Pedro II.', en: 'Caricature of the Brazilian emperor Dom Pedro II.', es: 'Caricatura del emperador brasileño Dom Pedro II.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook2.jpg' },
            { id: '27', titulo: { ptBR: 'Palhaço Amendoim Alegria', en: 'Amendoim Alegria Clown', es: 'Payaso Amendoim Alegria' }, descricao: { ptBR: 'Mascote para o palhaço Amendoim Alegria.', en: 'Mascot for the clown Amendoim Alegria.', es: 'Mascota para el payaso Amendoim Alegria.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_coursebook3.jpg' },
            { id: '28', titulo: { ptBR: 'Jogos de Natal', en: 'Christmas Games', es: 'Juegos de Navidad' }, descricao: { ptBR: 'Tabuleiro para jogo com tema de Natal.', en: 'Board for a Christmas-themed game.', es: 'Tablero para un juego con temática navideña.' }, categoria: 'publi', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_illustration-boardgamechristmas.jpg' },
            { id: '29', titulo: { ptBR: 'Caricatura Thiago Ventura', en: 'Thiago Ventura Caricature', es: 'Caricatura de Thiago Ventura' }, descricao: { ptBR: 'Caricatura para projeto de card game de comediantes.', en: 'Caricature for a comedians card game project.', es: 'Caricatura para un proyecto de juego de cartas de comediantes.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_Ventura.jpg' },
            { id: '30', titulo: { ptBR: 'Pula Gafanhoto', en: 'Jump Grasshopper', es: 'Salta Saltamontes' }, descricao: { ptBR: 'Ilustração para embalagem do jogo da empresa Estrela.', en: 'Illustration for the packaging of the Estrela company\'s game.', es: 'Ilustración para el empaque del juego de la empresa Estrela.' }, categoria: 'publi', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_packaging-illustration.jpg' },
            { id: '31', titulo: { ptBR: 'O estudante', en: 'The Student', es: 'El Estudiante' }, descricao: { ptBR: 'Personagem para campanha de volta às aulas.', en: 'Character for a back-to-school campaign.', es: 'Personaje para una campaña de regreso a clases.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-boy.jpg' },
            { id: '32', titulo: { ptBR: 'Caricatura Danilo Gentili', en: 'Danilo Gentili Caricature', es: 'Caricatura de Danilo Gentili' }, descricao: { ptBR: 'Caricatura para projeto de card game de comediantes.', en: 'Caricature for a comedians card game project.', es: 'Caricatura para un proyecto de juego de cartas de comediantes.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_danilo.jpg' },
            { id: '33', titulo: { ptBR: 'Blanka', en: 'Blanka', es: 'Blanka' }, descricao: { ptBR: 'Fanart do personagem Blanka do Street Fighter.', en: 'Fanart of the character Blanka from Street Fighter.', es: 'Fanart del personaje Blanka de Street Fighter.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-braziliansoccer.jpg' },
            { id: '34', titulo: { ptBR: 'A jogadora', en: 'The Player (Female)', es: 'La Jugadora' }, descricao: { ptBR: 'Ilustração para incentivo do futebol feminino.', en: 'Illustration to encourage women\'s soccer.', es: 'Ilustración para fomentar el fútbol femenino.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-braziliansoccer2.jpg' },
            { id: '35', titulo: { ptBR: 'O Goleiro', en: 'The Goalkeeper', es: 'El Portero' }, descricao: { ptBR: 'Ilustração sobre futebol brasileiro.', en: 'Illustration about Brazilian soccer.', es: 'Ilustración sobre el fútbol brasileño.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-braziliansoccer3.jpg' },
            { id: '36', titulo: { ptBR: 'Caricatura Murilo Couto', en: 'Murilo Couto Caricature', es: 'Caricatura de Murilo Couto' }, descricao: { ptBR: 'Caricatura para projeto de card game de comediantes.', en: 'Caricature for a comedians card game project.', es: 'Caricatura para un proyecto de juego de cartas de comediantes.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_murilo couto.jpg' },
            { id: '37', titulo: { ptBR: 'Gamerboy', en: 'Gamerboy', es: 'Gamerboy' }, descricao: { ptBR: 'Ilustração de menino jogando vídeo game para livro didático.', en: 'Illustration of a boy playing a video game for a textbook.', es: 'Ilustración de un niño jugando un videojuego para un libro de texto.' }, categoria: 'character-design', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-gamer.jpg' },
            { id: '38', titulo: { ptBR: 'Estudiosa', en: 'Studious Girl', es: 'Estudiosa' }, descricao: { ptBR: 'Menina segurando material escolar para livro didático.', en: 'Girl holding school supplies for a textbook.', es: 'Niña sosteniendo útiles escolares para un libro de texto.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-girl.jpg' },
            { id: '39', titulo: { ptBR: 'Faala Mamute', en: 'Hey Mammoth', es: 'Hola Mamut' }, descricao: { ptBR: 'Fanart do cantor Jhonatan Alexandre do grupo Revelação.', en: 'Fanart of the singer Jhonatan Alexandre from the group Revelação.', es: 'Fanart del cantante Jhonatan Alexandre del grupo Revelação.' }, categoria: 'publi', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-mamute.jpg' },
            { id: '40', titulo: { ptBR: 'Caricatura Dihh Lopes', en: 'Dihh Lopes Caricature', es: 'Caricatura de Dihh Lopes' }, descricao: { ptBR: 'Caricatura para projeto de card game de comediantes.', en: 'Caricature for a comedians card game project.', es: 'Caricatura para un proyecto de juego de cartas de comediantes.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_Dihh Lopes.jpg' },
            { id: '41', titulo: { ptBR: 'Cinema com Filósofos', en: 'Cinema with Philosophers', es: 'Cine con Filósofos' }, descricao: { ptBR: 'Ilustração de dois filósofos em um cinema para app didático.', en: 'Illustration of two philosophers in a cinema for an educational app.', es: 'Ilustración de dos filósofos en un cine para una aplicación educativa.' }, categoria: 'publi', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_publicitary-editorialillustration-philosophy_in_cinema.jpg' },
            { id: '42', titulo: { ptBR: 'Caricatura Afonso Padilha', en: 'Afonso Padilha Caricature', es: 'Caricatura de Afonso Padilha' }, descricao: { ptBR: 'Caricatura para projeto de card game de comediantes.', en: 'Caricature for a comedians card game project.', es: 'Caricatura para un proyecto de juego de cartas de comediantes.' }, categoria: 'caricatura', imagemUrl: '/assets/img/portfolio/humorismo_afonso padilha.jpg' },
            { id: '43', titulo: { ptBR: 'Ahhhh, o verão!', en: 'Ahhh, Summer!', es: '¡Ahhh, el Verano!' }, descricao: { ptBR: 'Criança na piscina curtindo um dia de sol.', en: 'Child in the pool enjoying a sunny day.', es: 'Niño en la piscina disfrutando de un día soleado.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/021_01_i_u4_cknB_booklet_m-01.jpg' },
            { id: '44', titulo: { ptBR: 'Embaixadinha', en: 'Juggling', es: 'Dominadas' }, descricao: { ptBR: 'Menino fazendo embaixadinhas com uma bola.', en: 'Boy juggling a ball.', es: 'Niño haciendo dominadas con un balón.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/021_02_i_u4_cknB_booklet_m-01.jpg' },
            { id: '45', titulo: { ptBR: 'Chuva na janela', en: 'Rain on the Window', es: 'Lluvia en la Ventana' }, descricao: { ptBR: 'Menino olhando pela janela em um dia chuvoso.', en: 'Boy looking out the window on a rainy day.', es: 'Niño mirando por la ventana en un día lluvioso.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/024_01_i_u4_cknB_booklet_m_Prancheta 1.jpg' },
            { id: '46', titulo: { ptBR: 'Brincando com barbantes', en: 'Playing with Strings', es: 'Jugando con Hilos' }, descricao: { ptBR: 'Menina indígena brincando com um barbante.', en: 'Indigenous girl playing with a string.', es: 'Niña indígena jugando con un hilo.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/SPE_REG_NV22_RR_EF3_HIS_AL-I007_Prancheta 1.jpg' },
            { id: '47', titulo: { ptBR: 'Montando quebra-cabeças', en: 'Assembling Puzzles', es: 'Armando Rompecabezas' }, descricao: { ptBR: 'Grupo de crianças montando um quebra-cabeças de mapa.', en: 'Group of children assembling a map puzzle.', es: 'Grupo de niños armando un rompecabezas de mapa.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/cleriston.ribeiro_theclassrom textbook.jpg' },
            { id: '48', titulo: { ptBR: 'O trabalho', en: 'The Work', es: 'El Trabajo' }, descricao: { ptBR: 'Ilustração em traços para um aplicativo educativo.', en: 'Line illustration for an educational application.', es: 'Ilustración en trazos para una aplicación educativa.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/CIE_2_ANO_UND_4_PL4_I004-01.jpg' },
            { id: '49', titulo: { ptBR: 'Papai Noel na praia (Sol)', en: 'Santa at the Beach (Sun)', es: 'Papá Noel en la Playa (Sol)' }, descricao: { ptBR: 'Papai Noel tomando sol em uma praia no verão brasileiro.', en: 'Santa Claus sunbathing on a beach in the Brazilian summer.', es: 'Papá Noel tomando el sol en una playa en el verano brasileño.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/noel-01.jpg' },
            { id: '50', titulo: { ptBR: 'Papai Noel na praia (Presentes)', en: 'Santa at the Beach (Presents)', es: 'Papá Noel en la Playa (Regalos)' }, descricao: { ptBR: 'Papai Noel carregando presentes pela praia.', en: 'Santa Claus carrying presents on the beach.', es: 'Papá Noel llevando regalos por la playa.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/noel-02.jpg' },
            { id: '51', titulo: { ptBR: 'Samba de Natal', en: 'Christmas Samba', es: 'Samba de Navidad' }, descricao: { ptBR: 'Ilustração do Papai Noel no Brasil com samba.', en: 'Illustration of Santa Claus in Brazil with samba.', es: 'Ilustración de Papá Noel en Brasil con samba.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/noel-03.jpg' },
            { id: '52', titulo: { ptBR: '...E mais cidade', en: '...And More City', es: '...Y Más Ciudad' }, descricao: { ptBR: 'Ilustração de cidade para abertura de capítulo de livro.', en: 'Illustration of a city for a book chapter opening.', es: 'Ilustración de una ciudad para la apertura de un capítulo de un libro.' }, categoria: 'editorial', imagemUrl: '/assets/img/portfolio/SPE_REG_NV21_MS_EF5_GEO_LA-I007.jpg' }
        ]
    },
    contato: {
        titulo: { ptBR: "Contato", en: "Contact", es: "Contacto" },
        localizacao: "São Paulo - SP",
        email: "cleristonrib@gmail.com",
        telefone: "55+(11) 99353-3001"
    }
};

async function seedDatabase() {
    console.log('Iniciando script de seeding...');
    if (!serviceAccount.project_id) {
        console.error('ERRO: O arquivo serviceAccountKey.json parece inválido ou não foi encontrado.');
        return;
    }
    if (admin.apps.length === 0) {
        admin.initializeApp({
            credential: admin.credential.cert(serviceAccount)
        });
    }
    const db = admin.firestore();
    const clientRef = db.collection('clientes').doc(CLIENT_ID);
    try {
        await clientRef.set({ siteData });
        console.log('✅ SUCESSO! Banco de dados semeado com todos os 52 itens do portfólio.');
    } catch (error) {
        console.error('❌ ERRO: Falha ao semear o banco de dados.', error);
    }
}
seedDatabase();